apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp250228
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp250228 
  name: goapp250228
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: goapp250228 
